# -*- coding: utf-8 -*-
"""notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zMonEg_V5Mit_hCDPGcAuRtDoQ-XdBlV

# Proyek Klasifikasi Gambar: [CIFAR-10 Dataset]
- **Nama:** [Dewa Bagus Putu Arya Dhananjaya]
- **Email:** [dewadhanan@gmail.com]
- **ID Dicoding:** [dewadhanan25]

## Import Semua Packages/Library yang Digunakan
"""

!pip install tensorflow
!pip install tensorflowjs

## Import Semua Packages/Library yang Digunakan
import os
import warnings
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import tensorflowjs as tfjs
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Reproducibility
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)
print("TensorFlow version:", tf.__version__)

"""## Data Preparation

### Data Loading
"""

# ====== LOAD DATASET (CIFAR-10; >1000 images) ======

# CIFAR-10: 60000 images (50000 train + 10000 test), 10 classes
(x_train_full, y_train_full), (x_test, y_test) = keras.datasets.cifar10.load_data()
y_train_full = y_train_full.flatten()
y_test = y_test.flatten()

# Combine and then split to get train/val/test as requested
# We'll take x_train_full (50000) and split into train + val
x_train, x_val, y_train, y_val = train_test_split(
    x_train_full, y_train_full, test_size=0.1, random_state=SEED, stratify=y_train_full
)
print("Train:", x_train.shape, "Val:", x_val.shape, "Test:", x_test.shape)

# Normalize images to [0,1]
x_train = x_train.astype("float32") / 255.0
x_val = x_val.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

# Parameters
IMG_HEIGHT, IMG_WIDTH, IMG_CH = x_train.shape[1:]
BATCH_SIZE = 64
NUM_CLASSES = 10
EPOCHS = 25

# Definisikan nama-nama kelas untuk dataset CIFAR-10
class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck']

# Untuk menampilkan nama kelas
print("Kelas-kelas dalam dataset:")
for i, class_name in enumerate(class_names):
    print(f"{i}: {class_name}")

plt.figure(figsize=(10, 10))
for i in range(25): # Menampilkan 25 gambar pertama
    plt.subplot(5, 5, i + 1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(x_train[i]) # Menggunakan x_train dari konteks
    # y_train adalah array 1D, jadi langsung gunakan indeks
    plt.xlabel(class_names[y_train[i]])
plt.show()

"""### Data Preprocessing

#### Split Dataset
"""

# ====== DATA AUGMENTATION (ImageDataGenerator) ======

# This helps generalization and helps reach higher test accuracy
train_datagen = ImageDataGenerator(
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True,
    zoom_range=0.1,
    fill_mode='reflect'
)
train_generator = train_datagen.flow(x_train, y_train, batch_size=BATCH_SIZE, shuffle=True, seed=SEED)

# Validation / test generators (no augmentation)
val_datagen = ImageDataGenerator()
val_generator = val_datagen.flow(x_val, y_val, batch_size=BATCH_SIZE, shuffle=False)

test_datagen = ImageDataGenerator()
test_generator = test_datagen.flow(x_test, y_test, batch_size=BATCH_SIZE, shuffle=False)

# Untuk menampilkan beberapa contoh gambar dari dataset dan membaginya menjadi 4 kelas
plt.figure(figsize=(12, 12))
for i in range(4):  # Menampilkan 4 kelas
    # Ambil indeks gambar dari kelas saat ini
    class_indices = np.where(y_train == i)[0]
    # Ambil 4 gambar pertama dari kelas tersebut
    for j in range(4):
        idx = class_indices[j]
        plt.subplot(4, 4, i * 4 + j + 1)
        plt.xticks([])
        plt.yticks([])
        plt.grid(False)
        plt.imshow(x_train[idx])
        plt.xlabel(class_names[y_train[idx]])
plt.suptitle("Contoh Gambar dari Dataset CIFAR-10 (4 Kelas Pertama)", y=1.02, fontsize=16)
plt.tight_layout()
plt.show()

# ====== Filter Dataset for 4 Classes ======

# Choose 4 classes to keep (e.g., airplane, automobile, bird, cat)
selected_classes = [0, 1, 2, 3] # Indices for 'airplane', 'automobile', 'bird', 'cat'

# Filter training data
train_indices = np.isin(y_train, selected_classes)
x_train_4_classes = x_train[train_indices]
y_train_4_classes = y_train[train_indices]

# Filter validation data
val_indices = np.isin(y_val, selected_classes)
x_val_4_classes = x_val[val_indices]
y_val_4_classes = y_val[val_indices]

# Filter test data
test_indices = np.isin(y_test, selected_classes)
x_test_4_classes = x_test[test_indices]
y_test_4_classes = y_test[test_indices]

# Update NUM_CLASSES
NUM_CLASSES = len(selected_classes)

print(f"Dataset filtered to {NUM_CLASSES} classes.")
print("Filtered Train:", x_train_4_classes.shape, "Filtered Val:", x_val_4_classes.shape, "Filtered Test:", x_test_4_classes.shape)

# Update the generators to use the filtered data
train_generator = train_datagen.flow(x_train_4_classes, y_train_4_classes, batch_size=BATCH_SIZE, shuffle=True, seed=SEED)
val_generator = val_datagen.flow(x_val_4_classes, y_val_4_classes, batch_size=BATCH_SIZE, shuffle=False)
test_generator = test_datagen.flow(x_test_4_classes, y_test_4_classes, batch_size=BATCH_SIZE, shuffle=False)

# Update class_names to reflect the selected classes
class_names_4_classes = [class_names[i] for i in selected_classes]
print("\nSelected classes:", class_names_4_classes)

"""## Modelling"""

# ====== BUILD MODEL (Kriteria: Sequential + Conv2D + Pooling) ======
def build_cnn_model(input_shape=(IMG_HEIGHT, IMG_WIDTH, IMG_CH), num_classes=NUM_CLASSES):
    model = keras.Sequential([
        layers.Input(shape=input_shape),

        layers.Conv2D(64, (3,3), padding='same', activation='relu'),
        layers.BatchNormalization(),
        layers.Conv2D(64, (3,3), padding='same', activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2,2)),
        layers.Dropout(0.25),

        layers.Conv2D(128, (3,3), padding='same', activation='relu'),
        layers.BatchNormalization(),
        layers.Conv2D(128, (3,3), padding='same', activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2,2)),
        layers.Dropout(0.35),

        layers.Conv2D(256, (3,3), padding='same', activation='relu'),
        layers.BatchNormalization(),
        layers.Conv2D(256, (3,3), padding='same', activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2,2)),
        layers.Dropout(0.4),

        layers.Flatten(),
        layers.Dense(512, activation='relu'),
        layers.BatchNormalization(),
        layers.Dropout(0.5),
        layers.Dense(num_classes, activation='softmax')
    ])
    return model

model = build_cnn_model()
model.summary()

# ====== COMPILE MODEL ======
initial_learning_rate = 1e-3
optimizer = keras.optimizers.Adam(learning_rate=initial_learning_rate)
model.compile(
    optimizer=optimizer,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# ====== CALLBACKS: LR SCHEDULE, EarlyStopping, Checkpoint ======
callbacks = []

# ReduceLROnPlateau
lr_reducer = keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss',   # Pantau val_loss
    factor=0.5,           # Turunkan LR menjadi setengah jika stagnan
    patience=3,           # Jika val_loss tidak membaik selama 3 epoch
    min_lr=1e-6,          # LR minimum
    verbose=1
)
callbacks.append(lr_reducer)

# EarlyStopping
early_stop = keras.callbacks.EarlyStopping(
    monitor='val_loss',   # Pantau val_loss
    patience=7,           # Hentikan training jika val_loss tidak membaik 7 epoch
    restore_best_weights=True,
    verbose=1
)
callbacks.append(early_stop)

# ModelCheckpoint
os.makedirs("checkpoints", exist_ok=True)
checkpoint_cb = keras.callbacks.ModelCheckpoint(
    "checkpoints/best_model.keras",
    monitor="val_accuracy",  # Simpan model terbaik berdasarkan val_accuracy
    save_best_only=True,
    verbose=1
)
callbacks.append(checkpoint_cb)

# ====== TRAIN ======
history = model.fit(
    train_generator,
    epochs=EPOCHS,
    validation_data=val_generator,
    callbacks=callbacks
)

"""## Evaluasi dan Visualisasi"""

# ====== PLOT ACCURACY & LOSS ======
def plot_history(history):
    fig, axs = plt.subplots(1,2,figsize=(14,5))
    # Accuracy
    axs[0].plot(history.history['accuracy'], label='train_acc')
    axs[0].plot(history.history['val_accuracy'], label='val_acc')
    axs[0].set_title('Accuracy')
    axs[0].set_xlabel('Epoch')
    axs[0].set_ylabel('Accuracy')
    axs[0].legend()
    # Loss
    axs[1].plot(history.history['loss'], label='train_loss')
    axs[1].plot(history.history['val_loss'], label='val_loss')
    axs[1].set_title('Loss')
    axs[1].set_xlabel('Epoch')
    axs[1].set_ylabel('Loss')
    axs[1].legend()
    plt.show()
plot_history(history)

# Muat model terbaik
best_model = keras.models.load_model("checkpoints/best_model.keras")
# Evaluasi model pada data test
print("\n--- Evaluating Model on Test Data ---")
test_loss, test_accuracy = best_model.evaluate(test_generator)
print(f"Test Loss: {test_loss:.4f}")
print(f"Test Accuracy: {test_accuracy:.4f}")

# Prediksi pada data test yang sudah difilter 4 kelas
y_pred_probs = best_model.predict(test_generator)
y_pred = np.argmax(y_pred_probs, axis=1)

# Classification Report
print("\n--- Classification Report ---")
print(classification_report(y_test_4_classes, y_pred, target_names=class_names_4_classes))

# Confusion Matrix
print("\n--- Confusion Matrix ---")
cm = confusion_matrix(y_test_4_classes, y_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names_4_classes,
            yticklabels=class_names_4_classes)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix (4 Classes)')
plt.show()

"""## Konversi Model"""

# Buat folder jika belum ada
os.makedirs("saved_models", exist_ok=True)

# Export model ke format SavedModel
saved_model_path = "saved_models/cifar10_saved_model"
best_model.export(saved_model_path)
print(f"Model SavedModel berhasil disimpan di: {saved_model_path}")

# Konversi model Keras ke TFLite
converter = tf.lite.TFLiteConverter.from_keras_model(best_model)
tflite_model = converter.convert()

# Simpan model TFLite
tflite_model_path = "saved_models/cifar10_model.tflite"
with open(tflite_model_path, 'wb') as f:
    f.write(tflite_model)

print(f"Model TensorFlow Lite berhasil disimpan di: {tflite_model_path}")

# Folder tujuan untuk TFJS
tfjs_target_dir = "saved_models/cifar10_tfjs"

# Simpan model ke format TFJS
tfjs.converters.save_keras_model(best_model, tfjs_target_dir)
print(f"Model TensorFlow.js berhasil disimpan di: {tfjs_target_dir}")

"""## Inference (Optional)"""

# --- Abaikan warning UserWarning TF Lite ---
warnings.filterwarnings("ignore", category=UserWarning)

# --- Load TFLite model ---
tflite_model_path = "saved_models/cifar10_model.tflite"
interpreter = tf.lite.Interpreter(model_path=tflite_model_path)
interpreter.allocate_tensors()

# Ambil input dan output details
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# --- Fungsi prediksi TFLite ---
def tflite_predict(interpreter, x):
    """
    x: single image, shape (H, W, C), dtype float32
    """
    # TFLite expects batch dimension
    input_data = np.expand_dims(x, axis=0).astype(np.float32)
    interpreter.set_tensor(input_details[0]['index'], input_data)
    interpreter.invoke()
    output_data = interpreter.get_tensor(output_details[0]['index'])
    return np.argmax(output_data, axis=1)[0]

# --- Contoh inference ---
# Ambil beberapa gambar dari test set (pastikan ini 4 kelas yang difilter)
num_samples = 5
sample_images = x_test_4_classes[:num_samples]
sample_labels = y_test_4_classes[:num_samples]

plt.figure(figsize=(15,5))
for i, img in enumerate(sample_images):
    pred_class = tflite_predict(interpreter, img)
    true_class = sample_labels[i]

    plt.subplot(1, num_samples, i+1)
    plt.imshow(img)
    plt.title(f"Pred: {class_names_4_classes[pred_class]}\nTrue: {class_names_4_classes[true_class]}")
    plt.axis('off')
plt.show()

!pip freeze requirements.txt